version: "3"
services:
    recipe_api:
        restart: always
        build: ./api/recipe_api
        container_name: "recipe_api"
        environment:
        - APP_ID=recipe_api
        - LOG_LEVEL=debug
        - URL_MONGO=mongodb://recipe:recipe@mongodb/recipe?authSource=admin
        ports:
            - "8000:3000"
    mongodb:
        image: mongo:latest
        container_name: "mongodb_recipe"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=recipe
            - MONGO_INITDB_ROOT_PASSWORD=recipe
            - MONGO_INITDB_DATABASE=admin
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
  
volumes:
  mongodata:
    driver: local
